config/routes.rb
Rails.application.routes.draw do

  root to: 'lists#index'
  resources :user_sessions, only:[:new,:create,:destroy]
  resources :users,:constraints => {:id  => /[0-9]+/ }
  resources :lists,:constraints => {:id  => /[0-9]+/ } do
    member do
      put :like
      delete :like, action: :unlike
    end
  end
  resource :mypage, controller: :mypage, only:[:show]

  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'

  namespace :admin do
    resources :users
  end

end

app/models/list.rb
# List
class List < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  has_many :user_lists ,dependent: :destroy
  has_many :fans ,through: :user_lists, source: :user

  validates :title, presence: true
  validates :items, presence: true
  validates :owner, presence: true

  default_scope -> { includes(:owner) }

  # items の値をリストで取得する
  # 改行コード区切りでリスト化された値を得る
  # @return [Array] item [String] のリスト
  def item_array
    items.split("\n");
  end

  # user がリストのファンか判定する
  #
  # @return [Boolean] ファンである時 true、それ以外はfalse
  def fan?(user)
    fans.include? user
  end

  # fan にuser を追加する。
  # すでにuser が fan であるときは rate の更新のみ行う
  # @param
  def add_fan(user, rating = 0)
    ul = user_lists.find_by(user_id:user.id)||UserList.new(user:user, list:self)
    ul.rating = rating
    ul.save!
  end

  # fan から user を削除する
  # @param [User] ユーザ
  def remove_fan(user)
    self.fans.delete(user)
  end

  def rating_of(user)
    ul = user_lists.find_by(user_id:user.id)
    (ul.present?)? ul.rating : 0
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :own_the_list?, only:[:edit, :update, :destroy]
  skip_before_filter :require_login, only: [:index, :show]

  LISTS_PAGE_SIZE = 24

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.includes(:fans).order(:created_at, :id).reverse_order
                 .page(params[:page]).per(LISTS_PAGE_SIZE)
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.owner = @current_user

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PUT /list/:id/like
  # PUT /list/:id/like.json
  def like
    @rating = rating_param[:rating] || 0
    puts @rating
    @list.add_fan(current_user, @rating)
  end

  # DELETE /list/:id/like
  # DELETE /list/:id/like.json
  def unlike
    @list.remove_fan(current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    rescue ActiveRecord::RecordNotFound => e
      render status: :not_found
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :description, :items, :memo)
    end

    def rating_param
      params.permit(:rating)
    end

    # 操作対象のリストのオーナーがログインユーザであることを確認
    # オーナーでなければ元のページかルートに戻す
    def own_the_list?
      if current_user.id != @list.owner_id
        respond_to do |format|
          format.html {
            alert_message = "You are not the owner of the list."
            if request.referer.nil?
              redirect_to :root, alert: alert_message
            else
              redirect_to :back, alert: alert_message
            end
          }
          format.json { status :forbidden }
        end
      end
    end
end

app/views/lists/_form.html.slim
= form_for @list, html:{class:'list-form' } do |f|
  - if @list.errors.any?
    .alert.alert-danger
    #error_explanation
      strong = "#{pluralize(@list.errors.count, "error")} prohibited this list from being saved:"
      ul
        - @list.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :title, class:"control-label"
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :description, class: "control-label"
    = f.text_area :description, class: "form-control", rows:5
  .form-group
    = f.label :items, class: "control-label"
      span = t('activerecord.attributes.list.items')
      span.notice = t('activerecord.attributes.list.items_notice')
    = f.text_area :items, class: "form-control", rows:15
  .form-group
    = f.label :memo, class: "control-label"
    = f.text_area :memo, class: "form-control", rows:5
  .form-group
    = f.submit class: "btn btn-default"
    = link_to t('helpers.submit.cancel'), _back_url, class: "btn btn-default"

app/views/lists/edit.html.slim
h1 = t('views.list.edit')

== render 'form'

app/views/lists/index.html.slim
.page-header
  .container
    .row
      .col-md-6.col-xs-6
        h1 = t('activerecord.models.list')
      .col-md-6.col-xs-6
        h1.text-right
          = link_to t('views.list.new'), new_list_path, class:"btn btn-default navbar-btn"

.container-fluid
  .row
    = page_entries_info @lists
  .row
    - @lists.each do |list|
      .col-xs-12.col-sm-6.col-md-4.col-lg-3
        = link_to(list, class:'lists') do
          .title
            = gravator_icon(list.owner,size:20, class:'gravator-icon', alt:'icon')
            - if list.fan? current_user
              span.star.glyphicon.glyphicon-star
            - else
              span.star.glyphicon.glyphicon-star-empty
            = list.title
          .desc = list.description
  .row
    = paginate @lists

app/views/lists/new.html.slim
h1 = t('views.list.new')

== render 'form'

app/views/lists/show.html.slim
.page-header
  .container
    .row
      .col-md-6.col-xs-6
        h1 = @list.title
      - if @list.owner == current_user
        .col-md-6.col-xs-6
          h1.text-right
            = link_to(edit_list_path(@list), class: "btn btn-default navbar-btn") do
              span.glyphicon.glyphicon-edit
              = t('views.list.edit')
            = link_to(list_path(@list), data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-default navbar-btn") do
              span.glyphicon.glyphicon-trash
              = t('views.list.delete')
    .row.owner
      .col-md-6.col-xs-6
        = gravator_icon(@list.owner, size:50, class:"gravator-icon", alt:"owner")
        span = "owner: #{@list.owner.email}"
      .col-md-6.col-xs-6
        .text-right
          - like = @list.fan?(current_user)? 'yes':''
          = form_tag({controller: :lists, action: :like}, remote:true, method: :put, id: :like, class: "like #{like}")
            = button_tag(class:"btn btn-default") do
              = t('views.list.like')
          = form_tag({controller: :lists, action: :like}, remote: true, method: :delete, id: :unlike, class: "unlike #{like}")
            = button_tag(class: "btn btn-default") do
              = t('views.list.unlike')
.container
  .list
    .desc
      .lbl 概要：
      = simple_format(h(@list.description))
    hr
    .items
      ul
        - @list.item_array.each do |item|
          li = item
    hr
    .memo.bg-info
      .lbl メモ:
      div = simple_format(h(@list.memo))

  div
    = link_to t('views.buttons.back'), :back, class: "btn btn-default"