config/routes.rb
Rails.application.routes.draw do

  root to: 'lists#index'
  resources :user_sessions, only:[:new,:create,:destroy]
  resources :users,:constraints => {:id  => /[0-9]+/ }
  resources :lists,:constraints => {:id  => /[0-9]+/ } do
    member do
      put :like
      delete :like, action: :unlike
    end
  end
  resource :mypage, controller: :mypage, only:[:show]

  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'

  namespace :admin do
    resources :users
  end

end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  before_action :set_user, only: [:show]

  # GET /users/1
  # GET /users/1.json
  def show
    expires_now
    @own_lists = @user.lists
    @favorite_lists = @user.favorite_lists
  end

  # # GET /users/1/edit
  # def edit
  #   if @user.id != current_user.id
  #     redirect_to action: :show, id: @user.id
  #   end
  # end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  # def update
  #   # TODO 自分かAdmin以外編集不可にする
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       # format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit }
  #       # format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /users/1
  # # DELETE /users/1.json
  # def destroy
  #   # TODO 自分かAdmin以外削除不可にする
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to :root, notice: 'User was successfully destroyed.' }
  #     # format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

end

app/views/mypage/show.html.slim
.page-header
  .container
    .row
      h2 = @user.email

.container
  ul.nav.nav-justified.nav-tabs[role="tablist"]
    li.active[role="presentation"]
      a[href="#favorite" aria-controls="favorite" role="tab" data-toggle="tab"]
        = t('views.mypage.favorlite_list')
    li[role="presentation"]
      a[href="#own" aria-controls="own" role="tab" data-toggle="tab"]
        = t('views.mypage.own_list')
  .tab-content
    #favorite.tab-pane.active[role="tabpanel"]
      table.table.table-striped.table-responsive.lists-table
        tbody
          - @favorite_lists.each do |list|
            tr
              td.owner
                = link_to user_path(list.owner) do
                  = gravator_icon(list.owner, size: 20, class:'gravator-icon', alt:'icon')
              td.title
                = link_to list_path(list) do
                  = list.title
              td.desc = list.description
              td.control

    #own.tab-pane[role='tabpanel']
      table.table.table-striped.table-responsive.lists-table
        tbody
          - @own_lists.each do |list|
            tr
              td.owner
                = link_to user_path(list.owner) do
                  = gravator_icon(list.owner, size: 20, class:'gravator-icon', alt:'icon')
              td.title
                = link_to list_path(list) do
                  = list.title
              td.desc = list.description
              td.control
                - if list.owner == current_user
                  = link_to edit_list_path(list) do
                    span.glyphicon.glyphicon-edit
                - if list.owner == current_user
                  = link_to list, data: {confirm: 'Are you sure?'}, method: :delete do
                    span.glyphicon.glyphicon-trash