config/routes.rb
Rails.application.routes.draw do

  root to: 'lists#index'
  resources :user_sessions, only:[:new,:create,:destroy]
  resources :users,:constraints => {:id  => /[0-9]+/ }
  resources :lists,:constraints => {:id  => /[0-9]+/ } do
    member do
      put :like
      delete :like, action: :unlike
    end
  end
  resource :mypage, controller: :mypage, only:[:show]

  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'

  namespace :admin do
    resources :users
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:root, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:root, notice: 'Logged out!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.slim
= form_tag user_sessions_path, method: :post, class: "form-horizontal" do
  .form-group
    = label_tag :email,'E-mail',class: "col-sm-2 control-label"
    .col-sm-6
      = text_field_tag :email,'', class: "form-control", placeholder: "xxxx@example.com"
  .form-group
    = label_tag :password, 'Password',class: "col-sm-2 control-label"
    .col-sm-6
      = password_field_tag :password,'', class: "form-control", placeholder:"password"
  .form-group
    .col-sm-offset-2.col-sm-6
      = submit_tag t('views.user.login'),class: "btn btn-default"
      = link_to t('helpers.submit.cancel'), _back_url, class: "btn btn-default"

app/views/user_sessions/new.html.slim
.page-header
  h1 Login

== render 'form'