config/routes.rb
Rails.application.routes.draw do

  root to: 'lists#index'
  resources :user_sessions, only:[:new,:create,:destroy]
  resources :users,:constraints => {:id  => /[0-9]+/ }
  resources :lists,:constraints => {:id  => /[0-9]+/ } do
    member do
      put :like
      delete :like, action: :unlike
    end
  end
  resource :mypage, controller: :mypage, only:[:show]

  get 'login' => 'user_sessions#new'
  post 'logout' => 'user_sessions#destroy'

  namespace :admin do
    resources :users
  end

end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[charset="UTF-8"]
    title
      = t('application.name')
    meta[name="viewport" content="width=device-width, initial-scale=1"]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"]
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to t('application.name'), :root, class: "navbar-brand"
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li = link_to t('application.list'), lists_url
            - if current_user
              li = link_to(t('application.mypage'), mypage_url)
            - if current_user && current_user.type == Admin::Type
              li = link_to(t('application.user'), admin_users_url)
            li
              a[href="#about"] About
          ul.nav.navbar-nav.navbar-right
            - if current_user
              li = link_to t('views.user.profile'), edit_user_path(current_user.id)
              li = link_to t('views.user.logout'), :logout, method: :post
            - else
              li = link_to t("views.user.register"), new_user_path
              li = link_to t("views.user.login"), :login
  .container
    .alerts
      - if flash[:notice]
        #notice.alert.alert-success.alert-dismissible[role="alert"]
          button[type="button" class="close" data-dismiss="alert" aria-label="Close"]
            span[aria-hidden="true"] &times;
          = flash[:notice]
      - if flash[:alert]
        #alert.alert.alert-warning.alert-dismissible[role="alert"]
          button[type="button" class="close" data-dismiss="alert" aria-label="Close"]
            span[aria-hidden="true"] &times;
          = flash[:alert]

    = yield

  footer.footer
    .container
      p.text-muted.text-center 2016